# Generated by Django 6.0.4 on 2026-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('closing_date', models.DateField()),
                ('company', models.CharField(max_length=99)),
                ('posted_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Techpark',
            },
        ),
    ]
