# Generated by Django 6.0.4 on 2026-04-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
