# Generated by Django 6.0.4 on 2026-04-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carres', '0002_job_address_job_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
