# Generated by Django 6.0.4 on 2026-04-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carres', '0003_alter_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='urlc',
            field=models.URLField(blank=True),
        ),
    ]
