# Generated by Django 6.0.4 on 2026-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carres', '0004_job_urlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
